### ISSUE TITLE
Do you have any working examples?

### ISSUE THREAD

**Issue by homanchou** [philipsens/monaco-xsd-code-completion#5]
I'm having trouble setting up a working example following your readme.

In particular, how do I get the first couple of import statements to work?

    import getBusinessPartnerDataXML from './GetBusinessPartnerData_7.xml'
    import commonMessageHeader2 from './CommonMessageHeader_2.xsd'
    import getBusinessPartnerData from './GetBusinessPartnerData_7.xsd'
    import ibisdoc from './ibisdoc.xsd'

It would be great if you had a working example so I can see what the xml/xsd's look like.

I tried just created my own xsd by pulling one off the internet, but on my setup, typescript is confused by the import statement saying can't find module or it's corresponding type declarations.  It's expecting js or typescript and doesn't understand xml/xsd.  What am I missing?

**Comment by Rafeethu** [comment]
Any update on this?

**Comment by philipsens** [comment]
The XSD imports are just as an example. You will have to provide them yourself. 

The idea behind this project is to create XML auto-completion based on an already existing XSD. If you don't have an XSD already it might be worth to make one, or to go with the default way Monaco suggests implementing simple autocompletion: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example example "Completion provider"

In the case you use Webpack, you'll need the fileLoader plugin to load files other than JS or TS.

This project is used within a project called "Frank!Flow" in this project there is one big XSD to verify the XML-configurations. That same XSD is used for auto-completion.
The implementation can be fount here: https://github.com/ibissource/frank-flow/blob/fcebf8d3966aef12540847234e205f90885888c0/src/frontend/app/Controller/CodeController.js
